# Generated by Django 3.1.5 on 2021-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherprofilemodel',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
    ]
