# Generated by Django 3.1.5 on 2021-04-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_control', '0002_publisherprofilemodel_book_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('edition', models.CharField(max_length=255)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.publisherprofilemodel')),
            ],
        ),
    ]
